public class PreventRecursionClass { 
    public static Boolean flag1 = false;
    public static Boolean flag2 = false;
    public static Boolean flag3 = false;
    public static Boolean flag4 = false;
    public static Boolean flag5 = false;
    public static Boolean flag51 = false;
    public static Boolean flag11 = false;
    public static Boolean flag21 = false;
    public static Boolean bookingBrokerageProcessed = false;
    public static Boolean bookflag1 = false;
    public static Boolean bookflag2 = false;
    public static Boolean bookflag3 = false;
    public static Boolean bookflag4 = false;
    public static Boolean bookflag5 = false;
    public static Boolean bookflag6 = false;
    public static Boolean bookflag7 = false;
    public static Boolean bookflag8 = false;
    public static Boolean bookflag10 = false;
    public static Boolean bookflag11 = false;
    
    public static Boolean taskflag1 = false;
    public static Boolean taskflag2 = false;
    public static Boolean taskflag3 = false;
    public static Boolean taskflag4 = false;
    public static Boolean taskflag5 = false;
    public static Boolean taskflag6 = false;
    public static Boolean taskflag7 = false;
    public static Boolean taskflag8 = false;
    public static Boolean taskflag9 = false;
    public static Boolean taskflag10 = false;
    public static Boolean PaymentFlag = false;
    public static Boolean KYCFlag = false;
    public static Integer i = 0;
    public static Boolean bookingFormSubmit = false;
    
    public static Boolean bookflag12 = false;
    public static Boolean bookflag13 = false;
    public static Boolean bookflag14 = false;
    public static Boolean bookflag15 = false;
    public static Boolean bookflag16 = false;
    public static Boolean bookflag17 = false;
    public static Integer sdrMethodCnt = 0;
    public static Integer WelcomeEmailCheckerMethodCnt = 0;
    
}